### ISSUE TITLE
Test Maps

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#1]
See: https://github.com/AssemblyScript/assemblyscript/issues/17

Seems like Maps may already be in the project?

**Comment by torch2424** [comment]
Also, may want to dig through https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly.d.ts

some more. May have array support, but just need it to compile and stuff :o. And could possibly expose Maps if sets work

**Comment by torch2424** [comment]
Made an issue also here: https://github.com/AssemblyScript/assemblyscript/issues/21

**Comment by dcodeIO** [comment]
Roadmap for real maps currently is:

* Find a universal way to hash values of any type, e.g., ints, floats, strings, classes etc. Either compile-time generic argument checks or Java-like `.hashCode` properties on the respective classes might work.
* Apply operator overloads. These are already set up but not yet checked when compiling the respective binary expression. Shouldn't be far.
* Having a working memory allocator/gc combo would definitely help using strings, sets, maps etc. Currently working on this.

**Comment by torch2424** [comment]
Totally found out that static classes, and re-exports work. Totally should have read the README more before I went ahead and made an issue.

**Comment by dcodeIO** [comment]
No worries, I'm actually just curious about how the first ever AssemblyScript gameboy emulator turns out :)

**Comment by torch2424** [comment]
Thanks!  Yeah it's coming along, I don't know if you saw, but thanks to your help, I turned my 4000+ line file and split it out! The CPU is about 85% done. Hopefully I can get some pixels drawn tonight 😄
