### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by windelbouwman** [torch2424/wasmBoy#123]
Just wanted to let you know that I just used your wasm project to emulate a gameboy in python: https://bitbucket.org/windel/ppci/src/default/examples/wasm/wasmboy.py

It performs reasonably well!

**Comment by torch2424** [comment]
You are welcome! Glad it worked out for you :)

A similar project by @CryZe is https://github.com/CryZe/wasmboy-rs 

I was planning on updating the README at some point soon with (more) derivative projects, do you mind if I add yours?

**Comment by windelbouwman** [comment]
No problem, please add to the readme! I am will also add sound support in the future.

**Comment by torch2424** [comment]
Awesome sounds good! I'll keep this issue open to remind myself in the meantime! I just started a new job, and I just loved so it may take me a while to get to it, but yeah! :)

**Comment by windelbouwman** [comment]
Now indeed it sounds pretty good. It was not easy to add proper sound support, but now I increased the buffer size, it works well with pygame.

**Comment by torch2424** [comment]
Sorry for the late reply, just saw this. Oh nice! Glad you got the sound figured out! Also, I added your project to the README in the PR I just referenced. And feel free to reach out at any time if you need any help! I plan on writing/cleaning up my docs soon, after I release the beta for my PWA I have been working on 😄

**Comment by windelbouwman** [comment]
Cool! Did you try to run the wasmboy.py to see its performance?
