### ISSUE TITLE
Find an alternative to JSZip

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#127]
After looking through our bundlephobia:
https://bundlephobia.com/result?p=wasmboy@0.1.1

It's half our bundle size:
https://bundlephobia.com/result?p=jszip@3.1.5

**Comment by CryZe** [comment]
I wonder how large a Rust WASM Zip Library would be 🤔

**Comment by CryZe** [comment]
The WASM file is ~70 KiB atm. But that's with a lot of panic handling in there, which isn't necessary. But wasm-snip seems broken atm, which would allow me to remove these. So we'll see where it ends up at after that works again.

**Comment by torch2424** [comment]
Awesome! Thanks for looking into this! 👍

**Comment by torch2424** [comment]
In case we can't find a wasm alternative. This is the only lightweight lib I could find, that most others will depend on:



https://www.npmjs.com/package/yauzl-promise

https://bundlephobia.com/result?p=yauzl-promise@2.1.3
