### ISSUE TITLE
Fix Link's Awakening Sword Crash

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#142]
Reported by @kyr0

Ironically, Link's awakening is the game I test the most on WasmBoy, and it totally works from what I can tell. I've gotten up to the first dungeon before.

Just to prove I'm not crazy, here's me with the sword running just fine 😄 

<img width="703" alt="screen shot 2018-09-12 at 10 55 30 am" src="https://user-images.githubusercontent.com/1448289/45443969-08393680-b67b-11e8-8121-dcc2bcc9dd9b.png">
<img width="701" alt="screen shot 2018-09-12 at 10 56 21 am" src="https://user-images.githubusercontent.com/1448289/45443970-08393680-b67b-11e8-85ad-1fc28de6f70d.png">

Any more info would be awesome @kyr0 ! 😄

**Comment by binji** [comment]
Maybe the original (non-color) version has issues?

**Comment by torch2424** [comment]
I play that one all the time too 😞 But I'll try it out tonight!

**Comment by kyr0** [comment]
Hi :)

You can find the ROM I use on emulator.games, it is 
Emulator.Games / ROMs / Gameboy / Legend Of Zelda, The - Link's Awakening (V1.2)

And well, I'm sorry but when I get the sword the owl says hello and then...

<img width="1432" alt="bildschirmfoto 2018-09-13 um 02 53 39" src="https://user-images.githubusercontent.com/454817/45460993-ce127800-b700-11e8-8505-754303661083.png">

Link decides to sleep again xD

Also the audio playback turns into white noise playback ;)

**Comment by torch2424** [comment]
Ahh Yes it is the non GBC one. That's odd that the GBC one works and the GB one does not. Thanks for raising the bug! Plan on working on accuracy in the coming weeks once I do some much needed maintenance on some other open source projects 😄

**Comment by binji** [comment]
I was curious, so I checked that rom's sha1sum and it's the same as the one that I have: 5ab63def958728933571c3b4f6af54db14f3f8b2

When I ran https://wasmboy.app with this rom I didn't get a crash when I grabbed the sword, so I'm wondering if you are doing something different to trigger it, perhaps.

**Comment by torch2424** [comment]
Oh Huh this is all super interesting, thanks for the investigation @binji ! 😄
