### ISSUE TITLE
Add Some Hosted Homebrew Titles

### ISSUE THREAD

**Issue by Miserlou** [torch2424/wasmBoy#159]
There are lots of awesome homebrew gameboy games out there - it'd be great if you could include some out of the box so we don't have to go hunt for ROMs to use on the website!

**Comment by torch2424** [comment]
Oh yeah definitely! :)

I currently have this implemented on my PWA for Wasmboy, [VaporBoy](https://github.com/torch2424/vaporBoy). But I can definitely add it to the debugger here. :)

**Comment by Miserlou** [comment]
Ah, didn't realize you were the same person! It was actually playing Tobu Tobu Girl on your website this week that led me down the whole rabbit whole of GB homebrew, and now I'm spending a sunday with the GBDK.. Cool!

I also found this website which seems to have a tonnnnn of public domain games, but I don't know which are actually worth playing: https://pdroms.de/files/gameboy/

**Comment by torch2424** [comment]
Oh nice! Glad that that all worked out haha! Yeah I'm thinking about getting Into GB Homebrew myself at some point.

And rad! Thanks for the link! :) I'll definitely look through. Right now I'm playing with a balancing act of games that are licensed appropriately vs games that won't crash on my emulator :')
