### ISSUE TITLE
Optional BIOS Selection

### ISSUE THREAD

**Issue by TiKevin83** [torch2424/wasmboy#191]
TASes which are being used for console accuracy verification rely on a slightly tweaked gbc_bios which recreates the initial register state of the GBC on a Game Boy Advance/Game Boy Player BIOS.  Optional BIOS selection before ROM selection would allow wasmBoy and/or vaporBoy to play back from this initial state or the GB/GBC bios state.

**Comment by torch2424** [comment]
Transferred this, as it currently needs to be fixed on this layer, before being moved into the PWA. 😄
