### ISSUE TITLE
Suggest optimizion for retrive image buffer.

### ISSUE THREAD

**Issue by MaxGraey** [torch2424/wasmboy#230]
Current method: https://github.com/torch2424/wasmBoy/blob/bcc26f197b9516f136d385b7ffad1d7734b7d4da/lib/graphics/worker/imageData.js#L4

could be optimize to:
```ts
import { GAMEBOY_CAMERA_WIDTH, GAMEBOY_CAMERA_HEIGHT } from '../constants';
// move out creation of buffers, which is not cheap
const imageDataArray = new Uint8ClampedArray(GAMEBOY_CAMERA_HEIGHT * GAMEBOY_CAMERA_WIDTH * 4);

// use non-closure version for method
export function getImageDataFromGraphicsFrameBuffer(wasmByteMemory) {
   for (let y = 0; y < GAMEBOY_CAMERA_HEIGHT; ++y) {
    let stride1 = y * (GAMEBOY_CAMERA_WIDTH * 3);
    let stride2 = y * (GAMEBOY_CAMERA_WIDTH * 4);
    for (let x = 0; x < GAMEBOY_CAMERA_WIDTH; ++x) {
      const pixelStart = stride1 + x * 3;
      const imageDataIndex = stride2 + (x << 2);
      imageDataArray[imageDataIndex + 0] = wasmByteMemory[pixelStart + 0];
      imageDataArray[imageDataIndex + 1] = wasmByteMemory[pixelStart + 1];
      imageDataArray[imageDataIndex + 2] = wasmByteMemory[pixelStart + 2];
      // Alpha, no transparency
      imageDataArray[imageDataIndex + 3] = 255;
    }
  }
  return imageDataArray;
}

```

**Comment by torch2424** [comment]
Rad perfect, makes sense. Was asking, so I can optimize some other things. Thanks! 😄

**Comment by MaxGraey** [comment]
Need to look. I just opened the random file and decide make this suggestion)

**Comment by MaxGraey** [comment]
btw did you see this?
https://github.com/torch2424/wasmBoy/issues/221

**Comment by torch2424** [comment]
@MaxGraey Yes! I have seen that, just haven't gotten around to it 😂

**Comment by MaxGraey** [comment]
Also are you try just do:
```ts
this.canvasImageData.data.set(this.imageDataArray);
```
instead:
```ts
for (let i = 0; i < this.imageDataArray.length; i++) {
   this.canvasImageData.data[i] = this.imageDataArray[i];
}
```
in [this line](https://github.com/torch2424/wasmBoy/blob/bcc26f197b9516f136d385b7ffad1d7734b7d4da/lib/graphics/graphics.js#L104)
?

**Comment by MaxGraey** [comment]
Also you could add `@inline` decorators for all functions in [this](https://github.com/torch2424/wasmBoy/blob/master/core/portable/portable.ts) and [this](https://github.com/torch2424/wasmBoy/blob/master/core/helpers/index.ts) files

**Comment by torch2424** [comment]
@MaxGraey Thanks! Yeah, I really need to learn/use the inline decorator. My plan was to use closure compiler over my JS output, but preserve function names in the output. And simply inline all of the functions that closure is inlining 😄 But I'll definitely go through and do those as well 😄 

Thank you SOOOO much this is all really appreciated!
