### ISSUE TITLE
Create an easy to embed iframe from other sites

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmboy#319]
Was asked to be able to copy an HTML snippet to embed on websites. Would be rad if there was an iframe we can host from Github Pages, that essentially is an all-in-one emulator. That when clicked on the iframe, would handle input and all that. And Settings can be passed in through query params. (Such as the rom URL, when to show mobile controls, etc...).

**Comment by eviL-Lizard** [comment]
Thank you sir
