### ISSUE TITLE
Allow Processing Zip Files

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#32]
Found this to be most supported / easiest:
https://www.npmjs.com/package/jszip

**Comment by dcodeIO** [comment]
Hmm, unzip in AssemblyScript sounds like fun as well :)

**Comment by torch2424** [comment]
@dcodeIO Oh yeah it definitely does 😄  

Perhaps we can make an npm module for it? wasm npm modules are "hot" right now

**Comment by torch2424** [comment]
Closed by #87
