### ISSUE TITLE
setJoypadState not working

### ISSUE THREAD

**Issue by FM1337** [torch2424/wasmboy#331]
As per the the wiki, I pass an object consisting of the following structure
```
                    let joyPadState = {
                      up: false,
                      right: false,
                      down: false,
                      left: false,
                      a: true,
                      b: false,
                      select: false,
                      start: false
                    };
```
to setJoypadState

followed by setting ``a`` to false and then passing that to setJoypadState after a few moments, and it does nothing, input is not received in game.

**Comment by FM1337** [comment]
So, I did get it to work, but it's really finicky sometimes. *shrug*

**Comment by torch2424** [comment]
@FM1337 Ah! Glad you got it figured out! That's a bit odd it's finicky sometimes! :hushed: I don't think I had that problem? :thinking: 

Then again, it may just be an async issue I didn't consider a while back :disappointed: 

But, let me know if I can help in any way! :smile:
