### ISSUE TITLE
Larger canvas sizes with same aspect ratio

### ISSUE THREAD

**Issue by redbrain** [torch2424/wasmboy#338]
I'd like to use wasmboy with a <canvas> sized (for example) 480x432.
This is still the aspect ratio of a GameBoy, but the <canvas> is automatically scaled down to 160x144 upon calling config().
Is it possible to run wasmboy at this larger canvas size?

**Comment by redbrain** [comment]
Realised that the canvas could simply be scaled with CSS. My bad.

**Comment by torch2424** [comment]
No worries at all! :smile: :tada:
