### ISSUE TITLE
LCDC should be initialised with BG on

### ISSUE THREAD

**Issue by tkers** [torch2424/wasmboy#353]
I noticed that the LCDC register (`0xFF40`) is initialised to `1001 0000`, which means the background (bit 0) is not enabled by default.

It is my understanding that the correct value on startup should be `1001 0001` instead. At least, when testing on a physical device (and a bunch of emulators), background rendering has always worked for me without touching the LCDC register.

**Comment by torch2424** [comment]
Yoooo! Thank you so much for finding and reporting this! 😄 I haven't had much time to work on the emulator as of late, but that's a super simple fix, so maybe after my next concert I'm doing, I'll go ahead and open a PR for that real quick! 😄 Thank you! 🙏🏾

**Comment by tkers** [comment]
I actually didn't realise you hadn't worked on this emulator for a while when I opened this issue 😄  Anyway, I had some time and managed to find where the initialisation happens and created a PR for this ☝️

**Comment by torch2424** [comment]
This should be published in 0.7.1 😄 🎉
