### ISSUE TITLE
Expose the memory map constants to JS and Rust

### ISSUE THREAD

**Issue by CryZe** [torch2424/wasmBoy#37]
By exporting the constants making up the memory map, both the JS and Rust emulator can just make use of the AssemblyScript constants. 

I just tested it and you can just export them as such:
```typescript
export const BLA: usize = 5;
```
```wat
(global $BLA (export "BLA") i32 (i32.const 5))
```

**Comment by torch2424** [comment]
Oh rad! That makes alot more sense than me having it in both places :p thanks! :)

**Comment by torch2424** [comment]
I'll get on this tonight! I may just pull in my Gameboy color branch, because it is becoming somewhat acceptable for gbc

**Comment by CryZe** [comment]
I noticed. It seems to work somewhat well for a lot of games now :D

**Comment by torch2424** [comment]
Thanks! I'm gonna start the constants thing now, hopefully I'll be done with it before I got to bed tonight. I'm currently doing laundry, and then I got a few more errands to run. So yeah haha!

**Comment by torch2424** [comment]
Did this in https://github.com/torch2424/wasmBoy/pull/39

Oh just saw your comment, I'll fix that later tonight! 

Also, the names are all terrible, I'll keep the current names as aliases down the line, but I will probably change them to something better later on :)
