### ISSUE TITLE
HDMA & DMA Issues

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#61]
Found by @ISSOtm

https://github.com/torch2424/wasmBoy/blob/f32b85f27999ba756e6ea0276dcade02b6434fea/wasm/memory/dma.ts#L51-L60

<img width="597" alt="screen shot 2018-04-09 at 12 41 23 pm" src="https://user-images.githubusercontent.com/1448289/38519027-589f4018-3bf3-11e8-9d47-70ed9b5c0038.png">

<img width="689" alt="screen shot 2018-04-09 at 12 42 16 pm" src="https://user-images.githubusercontent.com/1448289/38519072-79666eca-3bf3-11e8-86f3-aef756309c7f.png">

**Comment by torch2424** [comment]
HDMA stands for H-Blank HDMA, GDMA stands for General Purpose HDMA. Makes more sense than calling everything HDMA like the pandocs haha!

**Comment by torch2424** [comment]
Looking at how you're doing your OAM DMA, I think starting a DMA while one is already in progress would produce incorrect behavior

**Comment by ISSOtm** [comment]
https://github.com/torch2424/wasmBoy/blob/c6db402f0339aff106f0ebd82b5180ee69cd8abd/wasm/memory/dma.ts#L114
This does not apply wraparound, allowing WRAM to be overwritten by the DMA.

**Comment by torch2424** [comment]
Also, take a look at: https://github.com/binji/binjgb/commit/0d4de34deec4e53120c81ad0462f456bb0868f51

**Comment by torch2424** [comment]
The comment above fixes Donkey Kong Country :), see the discord exchange:

![screenshot_20180416-021501](https://user-images.githubusercontent.com/1448289/38800421-1706247c-411c-11e8-8a13-63a0046fcf06.png)
