### ISSUE TITLE
Fix Some More Performance Issues

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#69]
We lost a lot of speed in running the emu since https://github.com/torch2424/wasmBoy/commit/b49f76f92aa8d0a2278e20c636bd0f1b9461b1e0 .

After doing some research, the PR #38 was not the culprit, but rather #40 , I suspect that doing all the jumping between JS and Wasm to grab constants is adding a huge overhead, so we should simply cache these constants in function calls on initialize :).

Should also investigate PRs beyond #38 as well

**Comment by CryZe** [comment]
Wow, that almost sounds like it should be filed as a bug to the individual browsers, as the wasm clearly marks those as constant and thus should be heavily optimizable.

**Comment by torch2424** [comment]
Oh possibly, I'll see how I can access the chrome bug tracker, and things, thanks :)

**Comment by torch2424** [comment]
Found a place to issue a bug on chrome, need to make a reproducible though: https://bugs.chromium.org/p/v8/issues/entry
